server:
  port: 8080
spring:
  application:
    name: product
  #cloud:
  #  config:
  #    discovery:
  #      service-id: CONFIG
  #      enabled: true
  #    profile: dev
  redis:
    host: 192.168.20.134
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/han?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql=true:
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
logging:
  config: classpath:logback-spring.xml
